# Generated by Django 2.1 on 2018-08-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='folder',
            new_name='belong',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='folder',
            new_name='parent',
        ),
    ]
