# Generated by Django 2.1 on 2018-08-27 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180827_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='belong_folder', to='app.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='parent_folder', to='app.Folder'),
        ),
    ]
